// Generated by scripts/generate-wire.py. Do not edit.
package ai.shieldlabs;

import java.util.Map;

/** Schema-typed views. Values remain uncoerced for compatibility with older responses. */
final class WireModels {
    private WireModels() {}
    static final class HistoryRow {
        private final Map<?, ?> raw;
        HistoryRow(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue request_id() { return new WireValue.StringValue(raw.get("request_id")); }
        WireValue.StringValue session_id() { return new WireValue.StringValue(raw.get("session_id")); }
        WireValue.StringValue cookie_id() { return new WireValue.StringValue(raw.get("cookie_id")); }
        WireValue.StringValue domain() { return new WireValue.StringValue(raw.get("domain")); }
        WireValue.StringValue site_domain() { return new WireValue.StringValue(raw.get("site_domain")); }
        WireValue.StringValue user_hid() { return new WireValue.StringValue(raw.get("user_hid")); }
        WireValue.StringValue device_id() { return new WireValue.StringValue(raw.get("device_id")); }
        WireValue.StringValue visitor_id() { return new WireValue.StringValue(raw.get("visitor_id")); }
        WireValue.StringValue ip() { return new WireValue.StringValue(raw.get("ip")); }
        WireValue.StringValue os() { return new WireValue.StringValue(raw.get("os")); }
        WireValue.StringValue browser() { return new WireValue.StringValue(raw.get("browser")); }
        WireValue.StringValue device_type() { return new WireValue.StringValue(raw.get("device_type")); }
        WireValue.StringValue country() { return new WireValue.StringValue(raw.get("country")); }
        WireValue.StringValue connection_type() { return new WireValue.StringValue(raw.get("connection_type")); }
        WireValue.IntegerValue score() { return new WireValue.IntegerValue(raw.get("score")); }
        WireValue.StringValue score_details() { return new WireValue.StringValue(raw.get("score_details")); }
        WireValue.StringValue created_at() { return new WireValue.StringValue(raw.get("created_at")); }
        WireValue.IntegerValue ver() { return new WireValue.IntegerValue(raw.get("ver")); }
        WireValue.StringValue web_rtc_ip() { return new WireValue.StringValue(raw.get("web_rtc_ip")); }
        WireValue.StringValue web_rtc_country() { return new WireValue.StringValue(raw.get("web_rtc_country")); }
        WireValue.StringValue web_rtc_connection_type() { return new WireValue.StringValue(raw.get("web_rtc_connection_type")); }
        WireValue.StringValue webrtc_leak_ip() { return new WireValue.StringValue(raw.get("webrtc_leak_ip")); }
        WireValue.StringValue webrtc_leak_country() { return new WireValue.StringValue(raw.get("webrtc_leak_country")); }
        WireValue.StringValue webrtc_leak_connection_type() { return new WireValue.StringValue(raw.get("webrtc_leak_connection_type")); }
        WireValue.StringValue webrtc_leak_source() { return new WireValue.StringValue(raw.get("webrtc_leak_source")); }
        WireValue.BooleanValue is_vpn() { return new WireValue.BooleanValue(raw.get("is_vpn")); }
        WireValue.BooleanValue is_tor() { return new WireValue.BooleanValue(raw.get("is_tor")); }
        WireValue.BooleanValue is_proxy() { return new WireValue.BooleanValue(raw.get("is_proxy")); }
        WireValue.BooleanValue is_datacenter() { return new WireValue.BooleanValue(raw.get("is_datacenter")); }
        WireValue.BooleanValue is_abuser() { return new WireValue.BooleanValue(raw.get("is_abuser")); }
        WireValue.BooleanValue is_privacy_relay() { return new WireValue.BooleanValue(raw.get("is_privacy_relay")); }
        WireValue.BooleanValue is_stun_not_checked() { return new WireValue.BooleanValue(raw.get("is_stun_not_checked")); }
        WireValue.BooleanValue check_incomplete() { return new WireValue.BooleanValue(raw.get("check_incomplete")); }
        WireValue.BooleanValue is_antidetect() { return new WireValue.BooleanValue(raw.get("is_antidetect")); }
        WireValue.BooleanValue is_os_mismatch() { return new WireValue.BooleanValue(raw.get("is_os_mismatch")); }
        WireValue.BooleanValue is_os_not_detected() { return new WireValue.BooleanValue(raw.get("is_os_not_detected")); }
        WireValue.BooleanValue is_timezone_mismatch() { return new WireValue.BooleanValue(raw.get("is_timezone_mismatch")); }
        WireValue.BooleanValue is_js_disabled() { return new WireValue.BooleanValue(raw.get("is_js_disabled")); }
        WireValue.BooleanValue is_browser_automation() { return new WireValue.BooleanValue(raw.get("is_browser_automation")); }
        WireValue.BooleanValue is_incognito() { return new WireValue.BooleanValue(raw.get("is_incognito")); }
        WireValue.BooleanValue is_search_bot() { return new WireValue.BooleanValue(raw.get("is_search_bot")); }
        WireValue.BooleanValue is_suspicious_paid_click() { return new WireValue.BooleanValue(raw.get("is_suspicious_paid_click")); }
        WireValue.StringValue entry_url() { return new WireValue.StringValue(raw.get("entry_url")); }
        WireValue.StringValue utm_source() { return new WireValue.StringValue(raw.get("utm_source")); }
        WireValue.StringValue utm_medium() { return new WireValue.StringValue(raw.get("utm_medium")); }
        WireValue.StringValue utm_campaign() { return new WireValue.StringValue(raw.get("utm_campaign")); }
        WireValue.StringValue utm_content() { return new WireValue.StringValue(raw.get("utm_content")); }
        WireValue.StringValue utm_term() { return new WireValue.StringValue(raw.get("utm_term")); }
        WireValue.StringValue traffic_channel() { return new WireValue.StringValue(raw.get("traffic_channel")); }
        WireValue.StringValue traffic_channel_group() { return new WireValue.StringValue(raw.get("traffic_channel_group")); }
        WireValue.StringValue traffic_reason() { return new WireValue.StringValue(raw.get("traffic_reason")); }
        WireValue.StringValue referrer_domain() { return new WireValue.StringValue(raw.get("referrer_domain")); }
        WireValue.StringValue click_id_type() { return new WireValue.StringValue(raw.get("click_id_type")); }
    }
    static final class HistoryPage {
        private final Map<?, ?> raw;
        HistoryPage(Map<?, ?> raw) { this.raw = raw; }
        WireValue.ArrayValue data() { return new WireValue.ArrayValue(raw.get("data")); }
        WireValue.IntegerValue total() { return new WireValue.IntegerValue(raw.get("total")); }
    }
    static final class DomainProfile {
        private final Map<?, ?> raw;
        DomainProfile(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue Domain() { return new WireValue.StringValue(raw.get("Domain")); }
        WireValue.IntegerValue Weight() { return new WireValue.IntegerValue(raw.get("Weight")); }
        WireValue.StringValue Callback() { return new WireValue.StringValue(raw.get("Callback")); }
        WireValue.StringValue PublicKey() { return new WireValue.StringValue(raw.get("PublicKey")); }
        WireValue.StringValue Secret() { return new WireValue.StringValue(raw.get("Secret")); }
        WireValue.StringValue CreatedAt() { return new WireValue.StringValue(raw.get("CreatedAt")); }
    }
    static final class ScoreDetail {
        private final Map<?, ?> raw;
        ScoreDetail(Map<?, ?> raw) { this.raw = raw; }
        WireValue.IntegerValue Value() { return new WireValue.IntegerValue(raw.get("Value")); }
        WireValue.StringValue Description() { return new WireValue.StringValue(raw.get("Description")); }
    }
    static final class IdentificationScoredData {
        private final Map<?, ?> raw;
        IdentificationScoredData(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue request_id() { return new WireValue.StringValue(raw.get("request_id")); }
        WireValue.StringValue visitor_id() { return new WireValue.StringValue(raw.get("visitor_id")); }
        WireValue.StringValue device_id() { return new WireValue.StringValue(raw.get("device_id")); }
        WireValue.StringValue session_id() { return new WireValue.StringValue(raw.get("session_id")); }
        WireValue.StringValue cookie_id() { return new WireValue.StringValue(raw.get("cookie_id")); }
        WireValue.StringValue user_hid() { return new WireValue.StringValue(raw.get("user_hid")); }
        WireValue.StringValue domain() { return new WireValue.StringValue(raw.get("domain")); }
        WireValue.ObjectValue public_ip() { return new WireValue.ObjectValue(raw.get("public_ip")); }
        WireValue.ObjectValue local_ip() { return new WireValue.ObjectValue(raw.get("local_ip")); }
        WireValue.StringValue connection_type() { return new WireValue.StringValue(raw.get("connection_type")); }
        WireValue.StringValue os() { return new WireValue.StringValue(raw.get("os")); }
        WireValue.StringValue browser() { return new WireValue.StringValue(raw.get("browser")); }
        WireValue.StringValue device_type() { return new WireValue.StringValue(raw.get("device_type")); }
        WireValue.ObjectValue traffic_source() { return new WireValue.ObjectValue(raw.get("traffic_source")); }
        WireValue.IntegerValue risk_score() { return new WireValue.IntegerValue(raw.get("risk_score")); }
        WireValue.ArrayValue signals() { return new WireValue.ArrayValue(raw.get("signals")); }
        WireValue.ObjectValue detection_flags() { return new WireValue.ObjectValue(raw.get("detection_flags")); }
        WireValue.StringValue observed_at() { return new WireValue.StringValue(raw.get("observed_at")); }
    }
    static final class IdentificationScoredEvent {
        private final Map<?, ?> raw;
        IdentificationScoredEvent(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue event_type() { return new WireValue.StringValue(raw.get("event_type")); }
        WireValue.StringValue schema_version() { return new WireValue.StringValue(raw.get("schema_version")); }
        WireValue.StringValue created_at() { return new WireValue.StringValue(raw.get("created_at")); }
        WireValue.ObjectValue data() { return new WireValue.ObjectValue(raw.get("data")); }
    }
    static final class WebhookPingEvent {
        private final Map<?, ?> raw;
        WebhookPingEvent(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue event_type() { return new WireValue.StringValue(raw.get("event_type")); }
        WireValue.StringValue schema_version() { return new WireValue.StringValue(raw.get("schema_version")); }
        WireValue.StringValue created_at() { return new WireValue.StringValue(raw.get("created_at")); }
    }
    static final class TrafficSource {
        private final Map<?, ?> raw;
        TrafficSource(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue channel() { return new WireValue.StringValue(raw.get("channel")); }
        WireValue.StringValue referrer_domain() { return new WireValue.StringValue(raw.get("referrer_domain")); }
        WireValue.StringValue landing_url() { return new WireValue.StringValue(raw.get("landing_url")); }
        WireValue.StringValue click_id_type() { return new WireValue.StringValue(raw.get("click_id_type")); }
        WireValue.StringValue utm_source() { return new WireValue.StringValue(raw.get("utm_source")); }
        WireValue.StringValue utm_medium() { return new WireValue.StringValue(raw.get("utm_medium")); }
        WireValue.StringValue utm_campaign() { return new WireValue.StringValue(raw.get("utm_campaign")); }
        WireValue.StringValue utm_content() { return new WireValue.StringValue(raw.get("utm_content")); }
        WireValue.StringValue utm_term() { return new WireValue.StringValue(raw.get("utm_term")); }
    }
    static final class IpInfo {
        private final Map<?, ?> raw;
        IpInfo(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue ip() { return new WireValue.StringValue(raw.get("ip")); }
        WireValue.StringValue country() { return new WireValue.StringValue(raw.get("country")); }
    }
    static final class Signal {
        private final Map<?, ?> raw;
        Signal(Map<?, ?> raw) { this.raw = raw; }
        WireValue.StringValue name() { return new WireValue.StringValue(raw.get("name")); }
        WireValue.IntegerValue weight() { return new WireValue.IntegerValue(raw.get("weight")); }
    }
    static final class DetectionFlags {
        private final Map<?, ?> raw;
        DetectionFlags(Map<?, ?> raw) { this.raw = raw; }
        WireValue.BooleanValue vpn() { return new WireValue.BooleanValue(raw.get("vpn")); }
        WireValue.BooleanValue privacy_relay() { return new WireValue.BooleanValue(raw.get("privacy_relay")); }
        WireValue.BooleanValue browser_vpn_proxy() { return new WireValue.BooleanValue(raw.get("browser_vpn_proxy")); }
        WireValue.BooleanValue tor() { return new WireValue.BooleanValue(raw.get("tor")); }
        WireValue.BooleanValue proxy() { return new WireValue.BooleanValue(raw.get("proxy")); }
        WireValue.BooleanValue datacenter_ip() { return new WireValue.BooleanValue(raw.get("datacenter_ip")); }
        WireValue.BooleanValue abuser() { return new WireValue.BooleanValue(raw.get("abuser")); }
        WireValue.BooleanValue os_mismatch() { return new WireValue.BooleanValue(raw.get("os_mismatch")); }
        WireValue.BooleanValue os_not_detected() { return new WireValue.BooleanValue(raw.get("os_not_detected")); }
        WireValue.BooleanValue timezone_mismatch() { return new WireValue.BooleanValue(raw.get("timezone_mismatch")); }
        WireValue.BooleanValue anti_detect_browser() { return new WireValue.BooleanValue(raw.get("anti_detect_browser")); }
        WireValue.BooleanValue browser_automation() { return new WireValue.BooleanValue(raw.get("browser_automation")); }
        WireValue.BooleanValue ip_mismatch() { return new WireValue.BooleanValue(raw.get("ip_mismatch")); }
        WireValue.BooleanValue incognito() { return new WireValue.BooleanValue(raw.get("incognito")); }
        WireValue.BooleanValue search_bot() { return new WireValue.BooleanValue(raw.get("search_bot")); }
        WireValue.BooleanValue suspicious_paid_click() { return new WireValue.BooleanValue(raw.get("suspicious_paid_click")); }
        WireValue.BooleanValue javascript_disabled() { return new WireValue.BooleanValue(raw.get("javascript_disabled")); }
        WireValue.BooleanValue stun_not_checked() { return new WireValue.BooleanValue(raw.get("stun_not_checked")); }
        WireValue.BooleanValue check_incomplete() { return new WireValue.BooleanValue(raw.get("check_incomplete")); }
    }
    enum SearchType {
        REQUEST_ID, DEVICE_ID, USER_HID, VISITOR_ID, IP, SESSION_ID, COOKIE_ID;
        String wire() { return name().toLowerCase(java.util.Locale.ROOT); }
    }
    static final String HISTORY_PATH = "/api/v1/history/{search_type}/{value}";
    static String historyQuery(int limit, long offset) {
        return "?limit=" + limit + "&offset=" + offset;
    }
    static String[] profileHeaders(String domain) {
        return new String[] {"X-Shield-Domain", domain};
    }
}
