#!/usr/bin/env python3
"""Generate tolerant, schema-typed views used by the supported client."""
import argparse
import json
from pathlib import Path
import re
import sys

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = Path('src/main/java/ai/shieldlabs/WireModels.java')
MODELS = ('HistoryRow', 'HistoryPage', 'DomainProfile', 'ScoreDetail',
          'IdentificationScoredData', 'IdentificationScoredEvent', 'WebhookPingEvent',
          'TrafficSource', 'IpInfo', 'Signal', 'DetectionFlags')


def generate(doc):
    def resolve(schema):
        seen = set()
        while '$ref' in schema:
            ref = schema['$ref']
            if not ref.startswith('#/'):
                raise ValueError('Only local references are supported')
            if ref in seen:
                raise ValueError('Circular alias: ' + ref)
            seen.add(ref)
            schema = doc
            for key in ref[2:].split('/'):
                schema = schema[key.replace('~1', '/').replace('~0', '~')]
        return schema

    def kind(schema):
        schema = resolve(schema)
        typ = schema.get('type')
        if isinstance(typ, list):
            non_null = set(typ) - {'null'}
            if len(non_null) != 1:
                raise ValueError('Unsupported heterogeneous type list')
            typ = non_null.pop()
        if typ is None and ('anyOf' in schema or 'oneOf' in schema):
            types = {kind(s) for s in schema.get('anyOf', schema.get('oneOf', []))
                     if resolve(s).get('type') != 'null'}
            if len(types) != 1:
                raise ValueError('Unsupported heterogeneous union')
            return types.pop()
        return {'string': 'StringValue', 'integer': 'IntegerValue', 'number': 'NumberValue',
                'boolean': 'BooleanValue', 'array': 'ArrayValue', 'object': 'ObjectValue'}[typ]

    def ident(name):
        if not re.fullmatch(r'[A-Za-z_][A-Za-z_0-9]*', name):
            raise ValueError('Unsupported Java identifier: ' + name)
        return name

    def parameters(item, op, supported):
        # Operation-level definitions override path-item definitions with the same name/location.
        params = [resolve(p) for p in item.get('parameters', []) + op.get('parameters', [])]
        effective = {(p['in'], p['name']): p for p in params}
        for key, parameter in effective.items():
            if key not in supported and parameter.get('required', False):
                raise ValueError('Unsupported required parameter on ' + op['operationId'] + ': ' + str(key))
        return effective

    lines = ['// Generated by scripts/generate-wire.py. Do not edit.',
             'package ai.shieldlabs;', '', 'import java.util.Map;', '',
             '/** Schema-typed views. Values remain uncoerced for compatibility with older responses. */',
             'final class WireModels {', '    private WireModels() {}']
    for model in MODELS:
        schema = resolve(doc['components']['schemas'][model])
        if schema['type'] != 'object':
            raise ValueError(model + ' must remain an object')
        lines += [f'    static final class {model} {{', '        private final Map<?, ?> raw;',
                  f'        {model}(Map<?, ?> raw) {{ this.raw = raw; }}']
        for name, prop in schema['properties'].items():
            typ = kind(prop)
            lines.append(f'        WireValue.{typ} {ident(name)}() {{ return new WireValue.{typ}(raw.get({json.dumps(name)})); }}')
        lines += ['    }']
    # The actual operation, not only the reusable component, must still accept these parameters.
    operations = {op['operationId']: (path, item, op) for path, item in doc['paths'].items()
                  for method, op in item.items() if method == 'get'}
    path, item, op = operations['searchHistory']
    params = parameters(item, op, {('path', 'search_type'), ('path', 'value'),
                                   ('query', 'limit'), ('query', 'offset')})
    for location, name, expected in [('path', 'search_type', 'StringValue'), ('path', 'value', 'StringValue'),
                                     ('query', 'limit', 'IntegerValue'), ('query', 'offset', 'IntegerValue')]:
        if kind(params[location, name]['schema']) != expected:
            raise ValueError('Incompatible searchHistory parameter: ' + name)
    response = resolve(op['responses']['200'])['content']['application/json']['schema']
    if response.get('$ref') != '#/components/schemas/HistoryPage':
        raise ValueError('searchHistory response must map to HistoryPage')
    if '{search_type}' not in path or '{value}' not in path:
        raise ValueError('searchHistory path placeholders changed')
    lines += ['    enum SearchType {', '        ' + ', '.join(ident(v.upper()) for v in resolve(params['path', 'search_type']['schema'])['enum']) + ';',
              '        String wire() { return name().toLowerCase(java.util.Locale.ROOT); }', '    }',
              f'    static final String HISTORY_PATH = {json.dumps(path)};']
    lines += ['    static String historyQuery(int limit, long offset) {',
              '        return "?' + params['query', 'limit']['name'] + '=" + limit + "&' + params['query', 'offset']['name'] + '=" + offset;',
              '    }']
    profile_path, pitem, pop = operations['getDomainProfile']
    if profile_path != '/v1/profile':
        raise ValueError('Unsupported profile route: update the Management client adapter')
    pparams = list(parameters(pitem, pop, {('header', 'X-Shield-Domain')}).values())
    if not any(p['name'] == 'X-Shield-Domain' and p['in'] == 'header' and kind(p['schema']) == 'StringValue' for p in pparams):
        raise ValueError('Management domain header changed')
    domain_header = next(p for p in pparams if p['name'] == 'X-Shield-Domain')
    lines += ['    static String[] profileHeaders(String domain) {',
              '        return new String[] {' + json.dumps(domain_header['name']) + ', domain};', '    }']
    if resolve(pop['responses']['200'])['content']['application/json']['schema'].get('$ref') != '#/components/schemas/DomainProfile':
        raise ValueError('Profile response changed')
    for model, field, target, array in [
        ('HistoryPage', 'data', 'HistoryRow', True),
        ('IdentificationScoredData', 'signals', 'Signal', True),
        ('IdentificationScoredData', 'public_ip', 'IpInfo', False),
        ('IdentificationScoredData', 'local_ip', 'IpInfo', False),
        ('IdentificationScoredData', 'traffic_source', 'TrafficSource', False),
        ('IdentificationScoredData', 'detection_flags', 'DetectionFlags', False),
        ('IdentificationScoredEvent', 'data', 'IdentificationScoredData', False),
    ]:
        prop = doc['components']['schemas'][model]['properties'][field]
        if array:
            prop = resolve(prop)['items']
        if prop.get('$ref') != '#/components/schemas/' + target:
            raise ValueError('Unsupported nested shape: ' + model + '.' + field)
    for name, target in [('identification.scored', 'IdentificationScoredEvent'), ('webhook.ping', 'WebhookPingEvent')]:
        operation = doc['webhooks'][name]['post']
        body = resolve(operation['requestBody'])['content']['application/json']['schema']
        if body.get('$ref') != '#/components/schemas/' + target:
            raise ValueError('Webhook body changed: ' + name)
    # The runtime reads the common envelope through the scored view before dispatching on type.
    # Ping must retain the same declared names/kinds; differing event_type constants are expected.
    scored = doc['components']['schemas']['IdentificationScoredEvent']['properties']
    ping = doc['components']['schemas']['WebhookPingEvent']['properties']
    for field in ('event_type', 'schema_version', 'created_at'):
        if field not in ping or field not in scored or kind(ping[field]) != kind(scored[field]):
            raise ValueError('Incompatible shared webhook field: ' + field)
    lines += ['}', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--schema', type=Path, default=ROOT / 'resources/shieldlabs-api.yaml')
    parser.add_argument('--output-root', type=Path, default=ROOT)
    args = parser.parse_args()
    rendered = generate(yaml.safe_load(args.schema.read_text()))
    output = args.output_root / OUTPUT
    if args.check:
        if not output.exists() or output.read_text() != rendered:
            sys.exit('Wire models are stale. Run python3 scripts/generate-wire.py')
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered)


if __name__ == '__main__':
    main()
